import type { AnalysisReport, CategoryResult } from '../../types';
import { formatDate } from '../../utils/formatters';

function scoreToGrade(score: number): string {
  if (score >= 85) return 'A';
  if (score >= 70) return 'B';
  if (score >= 55) return 'C';
  if (score >= 40) return 'D';
  return 'F';
}

function buildHeader(report: AnalysisReport): string[] {
  const lines: string[] = [];
  lines.push(`# RepoRev Report: ${report.repo.owner}/${report.repo.repo}`);
  lines.push('');
  lines.push(`**Grade: ${report.grade}** (${report.overallScore}/100)`);
  lines.push(`*Analyzed on ${formatDate(report.analyzedAt)}*`);
  lines.push('');
  if (report.repoInfo.description) {
    lines.push(`> ${report.repoInfo.description}`);
    lines.push('');
  }
  if (report.techStack.length > 0) {
    lines.push(`**Tech Stack:** ${report.techStack.map((t) => t.name).join(', ')}`);
    lines.push('');
  }
  return lines;
}

function buildCategoryTable(categories: CategoryResult[]): string[] {
  const lines: string[] = [];
  lines.push('## Category Scores');
  lines.push('');
  lines.push('| Category | Score | Grade |');
  lines.push('|---|---|---|');
  for (const cat of categories) {
    lines.push(`| ${cat.label} | ${cat.score}/100 | ${scoreToGrade(cat.score)} |`);
  }
  lines.push('');
  return lines;
}

function buildBulletSection(
  title: string,
  items: string[],
  headingLevel: '##' | '###' = '##',
): string[] {
  if (items.length === 0) return [];
  const lines: string[] = [];
  lines.push(`${headingLevel} ${title}`);
  for (const item of items) {
    lines.push(`- ${item}`);
  }
  lines.push('');
  return lines;
}

function buildLlmInsights(report: AnalysisReport): string[] {
  if (!report.llmInsights) return [];
  const lines: string[] = [];
  lines.push('## AI Insights');
  lines.push('');
  lines.push(report.llmInsights.summary);
  lines.push('');
  lines.push(...buildBulletSection('AI-Identified Risks', report.llmInsights.risks, '###'));
  lines.push(
    ...buildBulletSection('AI Recommendations', report.llmInsights.recommendations, '###'),
  );
  return lines;
}

function buildFooter(): string[] {
  return ['---', '*Generated by [RepoRev](https://github.com) — GitHub Repository Review Tool*'];
}

export function reportToMarkdown(report: AnalysisReport): string {
  const lines: string[] = [
    ...buildHeader(report),
    ...buildCategoryTable(report.categories),
    ...buildBulletSection('Strengths', report.strengths),
    ...buildBulletSection('Risks', report.risks),
    ...buildBulletSection('Next Steps', report.nextSteps),
    ...buildLlmInsights(report),
    ...buildFooter(),
  ];

  return lines.join('\n');
}
