import type { AnalysisReport } from '../../types';
import { formatDate } from '../../utils/formatters';

export function reportToMarkdown(report: AnalysisReport): string {
  const lines: string[] = [];

  lines.push(`# RepoRev Report: ${report.repo.owner}/${report.repo.repo}`);
  lines.push('');
  lines.push(`**Grade: ${report.grade}** (${report.overallScore}/100)`);
  lines.push(`*Analyzed on ${formatDate(report.analyzedAt)}*`);
  lines.push('');

  if (report.repoInfo.description) {
    lines.push(`> ${report.repoInfo.description}`);
    lines.push('');
  }

  // Tech Stack
  if (report.techStack.length > 0) {
    lines.push(`**Tech Stack:** ${report.techStack.map((t) => t.name).join(', ')}`);
    lines.push('');
  }

  // Category Scores
  lines.push('## Category Scores');
  lines.push('');
  lines.push('| Category | Score | Grade |');
  lines.push('|---|---|---|');
  for (const cat of report.categories) {
    const catGrade =
      cat.score >= 85 ? 'A' :
      cat.score >= 70 ? 'B' :
      cat.score >= 55 ? 'C' :
      cat.score >= 40 ? 'D' : 'F';
    lines.push(`| ${cat.label} | ${cat.score}/100 | ${catGrade} |`);
  }
  lines.push('');

  // Strengths
  if (report.strengths.length > 0) {
    lines.push('## Strengths');
    for (const s of report.strengths) {
      lines.push(`- ${s}`);
    }
    lines.push('');
  }

  // Risks
  if (report.risks.length > 0) {
    lines.push('## Risks');
    for (const r of report.risks) {
      lines.push(`- ${r}`);
    }
    lines.push('');
  }

  // Next Steps
  if (report.nextSteps.length > 0) {
    lines.push('## Next Steps');
    for (const n of report.nextSteps) {
      lines.push(`- ${n}`);
    }
    lines.push('');
  }

  // LLM Insights
  if (report.llmInsights) {
    lines.push('## AI Insights');
    lines.push('');
    lines.push(report.llmInsights.summary);
    lines.push('');
    if (report.llmInsights.risks.length > 0) {
      lines.push('### AI-Identified Risks');
      for (const r of report.llmInsights.risks) {
        lines.push(`- ${r}`);
      }
      lines.push('');
    }
    if (report.llmInsights.recommendations.length > 0) {
      lines.push('### AI Recommendations');
      for (const r of report.llmInsights.recommendations) {
        lines.push(`- ${r}`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('*Generated by [RepoRev](https://github.com) — GitHub Repository Review Tool*');

  return lines.join('\n');
}
